### ISSUE TITLE
Types resolution fails for expect-puppeteer matchers

### ISSUE THREAD

**Issue by mulekick** [argos-ci/jest-puppeteer#598]
## 🐛 Bug Report

When writing tests with Typescript, the types resolution fails in the VSCode IDE (and maybe other code editors as well) for the ```jest-puppeteer``` globals :
- ```expect```
- ```browser```
- ```context```
- ```page```
- ```puppeteerConfig```
- ```jestPuppeteer```

## To Reproduce

1. Follow the installation procedure detailed in the "Getting started" section of ```jest-puppeteer``` README.
2. Create a ```*.test.ts``` file and write some basic tests involving ```jest-puppeteer``` globals.
3. Types resolution fails : Typescript flags globals as not found and ```expect-puppeteer``` matchers as nonexistent.
4. Types resolution for globals can be enabled by adding :
```typescript
import "jest-puppeteer";
import {expect} from "expect-puppeteer";
```
5. At this stage, ```expect-puppeteer``` matchers are nevertheless still flagged as nonexistent by Typescript.

## Expected behavior

Types resolution should work, globals and ```expect-puppeteer``` matchers should be available in the IDE for autocompletion and autocorrect.

## Link to repl or repo (highly encouraged)

[Repo here](https://github.com/mulekick/jest-puppeteer-issue)

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
 - CPU: (6) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 369.64 MB / 2.85 GB
 - Container: Yes
 - Shell: 5.2.15 - /bin/bash
## Binaries:
 - Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
 - npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm
## npmPackages:
 - expect-puppeteer: 10.1.1 => 10.1.1 
 - jest-environment-puppeteer: 10.1.1 => 10.1.1 
 - jest-puppeteer: 10.1.1 => 10.1.1 
```

**Comment by gregberge** [comment]
Fixed in #599

**Comment by jamesgpearce** [comment]
I'm still seeing this type error with a fresh NPM install.

<img width="454" alt="image" src="https://github.com/user-attachments/assets/b444a95d-9597-4541-8cc6-230992754ccf">

What might I be doing wrong?

## System:
 - OS: macOS 14.5
 - CPU: (8) arm64 Apple M2
 - Memory: 147.27 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 22.8.0 - /opt/homebrew/bin/node
 - npm: 10.9.0 - /opt/homebrew/bin/npm
 - pnpm: 9.1.4 - /opt/homebrew/bin/pnpm
 - bun: 1.1.28 - ~/.bun/bin/bun
## npmPackages:
 - jest-puppeteer: ^10.1.2 => 10.1.2

**Comment by mulekick** [comment]
This error happens if you're trying to call toMatchElement() with an argument that's not a Page | Frame | ElementHandle, which is strange because typescript flags it as a Page in your screenshot. Maybe there's a conflict with another jest based library ?

It would be great if I could clone a repo where the error occurs to see if I can reproduce it and investigate. Also, double check that you've done everything as regards to the [troubleshooting](https://github.com/argos-ci/jest-puppeteer?tab=readme-ov-file#typescript) section.

**Comment by mulekick** [comment]
@jamesgpearce I created a [pull request](https://github.com/tinyplex/tinybase/pull/188) in your repo to fix that 👍 maybe I'll update the docs here to be more explicit about the imports thing since ```10.1.2``` is in fact a breaking change from the DX point of view.
